### ISSUE TITLE
Corrupted or Empty PDF file?

### ISSUE THREAD

**Issue by seryafarma** [seryafarma/Freedom-of-Information-Act-Collections#13]
Hi @maartenmarx , when doing some EDA I notice that some of the PDF files are empty?

![image](https://user-images.githubusercontent.com/3274071/149035405-3e90e372-5975-4db1-aa6c-7001e3814901.png)

I was checking the zip file, but then I notice that they are also like that from the surfdrive:
![image](https://user-images.githubusercontent.com/3274071/149035513-49f4f057-382e-48b9-a7ca-4983110195cf.png)

Do you know if these documents are corrupted?
Do we have actually a script to download all the pdf from WOB Covid 19? Maybe we can redownload all of them again.

**Comment by seryafarma** [comment]
I just noticed that indeed the documents are corrupted, for example for the first document, I can get the pdf just fine at:

https://wobcovid19.rijksoverheid.nl/publicaties/561b8b6e6eb90efbfe4649fc9a5f2e05/besluit-en-lijst-van-documenten.pdf

While in my folder it is not openable 😞

**Comment by maartenmarx** [comment]
Excellent wortk @seryafarma , the download script is in `DocumentSplitting/ProbeerselsMarx/CollectPDFs.ipynb`.
I did it from the command line, using curl.

I suggest you check the files which are empty and simplhy download these again, using the spreadsheet with urls, and please use the same way of creating the filenames.

Of course, we get problems further on with the pdftohtml and the OCR as well....., because these then are also corrupted for these pdfs.

So maybe put these new pdfs in a spetarate folder, and redo all steps that I did just for them, also as a check for you that I did all correctly. What do you think? It may also help you understand what is going on.

Good luck!
maarten

**Comment by seryafarma** [comment]
@maartenmarx 

Do you have the file `OverviewReport.csv`? I have a file `PdfOverviewReport`

![image](https://user-images.githubusercontent.com/3274071/149132493-cf332677-5e27-4870-a20d-0233e913223b.png)

Do you maybe have also an updated notebook?

Kind regards, Fajar

**Comment by maartenmarx** [comment]
Hi @seryafarma ,

sorry, i guess it is in DocumentSplitting/MetaDataOverviewReport.xlsx

**Comment by seryafarma** [comment]
Hi @maartenmarx I found the rootcause.

Using curl, there is this error message for some documents:

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - De intrekkingsfunctie kan het intrekken van het certificaat niet controleren.
```

I managed to fix it in my notebook. I will upload my notebook to git.
